name: Build and Deploy Github Pages Files

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node 18
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install packages.json
      run: npm install   

    - name: Build
      run: npm run build
        
    - name: Update deployment for GitHub Pages
      env:
        ACTOR: ${{ github.actor }}
        AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
      run: |
        git status; \
        git config --global user.email $AUTHOR_EMAIL; \
        git config --global user.name $ACTOR; \
        if [[ `git status --porcelain` ]]; \
        then git add . && git commit -m"Auto update deployment folder" && echo "changes committed" && git push; \
        else echo "no changes to commit"; \
        fi
